version: '2'
services:
  backend-service:
    command: "./main"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/backend-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000